### ISSUE TITLE
Thermos 1614.49 - Blocks removal/dupe in unloaded chunks

### ISSUE THREAD

**Issue by vadimyer** [TCPR/Thermos#249]
Still experiencing issues with block removal/dupe when teleporting or walking away from a chunk where the block was **recently** built. Seems like a kind of save issue. Please @Robotia ._.

Some useful info, maybe. From bukkit.yml:
```
chunk-gc:
  enabled: true
  period-in-ticks: 3000
  load-threshold: 100
ticks-per:
  animal-spawns: 800
  monster-spawns: 20
  autosave: 0
```

From cauldron.yml:
```
settings:
  load-chunk-on-forge-tick: false
  check-entity-max-speeds: false
  chunk-gc-grace-period: 0
  check-entity-bounding-boxes: true
  load-chunk-on-request: true
  entity-bounding-box-max-size: 1000
  dump-materials: false
```

tileentities.yml:
```
settings:
  skip-tileentity-ticks: true
  prevent-invalid-tileentity-updates: true
```
